---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: sa-p8
spec:
  encryptedData:
    .dockerconfigjson: AgCVocJuy4Cyl10edd2wM6/fywOBblUHEwDOjjpihp17fDCnYfAn7n64qdDqKqiFZtOhh79rb9S1o8rRrJZ4JAf7mX/om5ZgnI23/XMMEUByq3cBI+4PelxAPTs6s1hcWoCU8Q/yqzbNNffwqydSg5fdgLXI1NXLiwHEI1Ob3CyH4BnlVAbEfYI3CiQ9APhrdBddvQi0kfNFZKGxtQdPIXnDq9sKP7/SW2cqbB+z11FojKLeAYlDtOlJu60KLz+8mra7M3OeKnqMEawxSvR/6OCx4hg3tIwk/NDL/AiGj0uyu1WJtcBLO/+OBc1iobnpGdEya2VT/Ewmhxo1PmYkQxyF3YJxkYudp2OiE83kuhuCZURUGRub0z4nckv1AKGZdk1NqttCjDAkFHX0YS+UTyiq6UfsfsNGsU6SPmz/uR9FJ6m3seztfl+uZkwvHfwE5g2S9aLEpzjYH1G3x/jjZbod+tsE5KXWy35YSBEOUlDr7tfTz6MdInQW8sP2KaaujwYfRUZQ2cU2SzEM8SVPqx0rk+lsbvPRFqtaFrqsVI2yqKafmOJxC/x8iNLFxoDHe5K4wGfxSClJTvGnH7K/axVpdjrwhVhrfwN4rveiNh3lZbWL9O0Mqig4OSFXB1XtDnLwzsltd/zH3bUCwh+CRJttW7bnzjPXcfiKu2u+RQLi1HPI7GLmUNYHAKd468MEVnZPlwFvTaALhVu/ssW9vRiCxXsINDmZKMHS+g1IKJMSh6MLNQik1m/is2KyRp5kGvac7Ce5BdHj7eAm/C7Jbv+3q0Yto5dZqcfxvQEz1YNNWdM0wQtg/GFrThMDaE2/JvqowPhXr2EGTFrQD52ba9iQueLnn4b6GPzXBmutDsarCCHaY7V1M5E+NjKgvhB2szJ/w5TGeA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: sa-p8
    type: kubernetes.io/dockerconfigjson
