---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: sa-p8
spec:
  encryptedData:
    .dockerconfigjson: AgCbFPq+/5AsqZyxcCz3OaNN281FjLLxPYkskFBqVblGvWD1dDbTAQAWCV8pNsz/LcPe1uYYdx7Vm0/PL+Yc/HzYoSXnEL/daGDUrnACVo8kpzY4NbSQp4xeUwy+4BsKWc5wZO1RJRE4sNFThcndllVhxe2vHD093hsEh1InXFchiSeTZWCco08Drpg1NlzyHA/dX7VmzXGciRaFUHb6nbvGd7+z4sQbmTxyrRPpl8Agv0inFmiU/aZpOTM8hf71VFE0H7ppVGsq2a4cK8OqrTGQyMasEhqd9/TKOPlEp43RzXR4zDqO5Ge2ZNOJjFkttsfLcoTTgZdMPYEc0FlUiu7VS0XEY8BsF3zSnDLwM7JC9tsgAFNUjyzAlTwywSM0/F9onUQwo4yMiyluv7QgxX7HJWxBilUqIofjV3gERtTzZP/59y+Qsybg3zN1Thur1554RRjQ5XLEcE6M6OmhfdIO610CfQXl6lTcXew/8f5Vn3lW+1GpyFGiPXetH9fZtxUCVXcZihUy/Ef/uT3CKBeXIuUyF58ksX/dEkG7L5lUbybwFFTywEBcVn8dZ56tjXRWTgmo13F1IOePAbiZRbGwWE1n0CifFwxkuIttLPyaPMILqSWkTP3XY2uHi5heFiwxWmWRrbNzbSEeCZPBXWhrUrxkTcLv2E+/RrFAXmv8O7cddWdH4ULigkdSsI/E0yYJt3GG0qaOREdkm0EmyObZE+rBaJ5l9YU5RCrxNyQWM/goYnjMREz3qwDUa1Pd5YGpPV2TgKTwCQzAuekzzip+PQeRM9yQMPFTdRm/G3TbEhJYIvF0LqMtm2rjIFppfW2weYghJpXX8bNU5nucCDKgvhvlNIt6ckAscGvhZAeh2IXkIcAuaxH/7Ws5ZYIU5PG5jVBd2kkNi1K+D053E9okQlgqiLHduQ92TwN3H4Oaw9DzNA8wwNvKnFWmNmOY2w==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: sa-p8
    type: kubernetes.io/dockerconfigjson
