---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: sa-p8
spec:
  encryptedData:
    .dockerconfigjson: AgAVA3qYQFhtY8F4OhFo1DGd/cT/UOhMuC7AoJOs8QUrz0KdzuKBmgSN/mwz3hfVGbHyLhPqHsjMZ1l9Np+0NTwNg3ViXN7FR/b4Ra4uYNm7mvDu87WZ020wVx3qlla+Ysq5//MDIuYHnMo5vIapflL2plh4q8z3fyYc5yUz2+2XoKtr8WGCcyfFYfwpK/vNFJRbL+SKeMC/OGa8GaJGPFATR9yBuN1Qq49A/DFyO8wUl9ysBa3vx3Bggdm26B2M6rCI+8Yd9YMxaipFRwpt5u9PErSnt5ppzAkUwD3DeF8ICy0TbKzbDpEIa5BjGzcbYqnZ+sxJdseb+She7Gu3vKqAbd3Ilc5rQoyGXMfe/BQHSZRTC3IYgzDJSQo8FGgHq+TLZG1eeWBbPm7xq/TRubRtbVViSbSFyrKRswQP85pnJrPhZ0/6Twer8Hjy0S35amMlxpyYMGTe7ieAPVamjKt8c0fn47UrKCTCmfKyh6NNg8es7w/CnAYyRDBXmVdLCWDnnLBN5o3XCULOfc5Z+18fCmiC0mW2UGy4Fzy4sYf8zHs+8LQ6s5JRZ3DPhTwnT4Gy4FLVvqyivfQ0yTCOZhiE74Bh7QDG9495RjWbNeUYcWAkv8tH9RxHR3wkX1oLmbj2jsm16eEy9CoIH28F8j3mSN8JUdKuIgAZ9fEk9Hu1viHNhtmDa6EhtPMHt0VRcnLmwHAuvbTLCqGWQPo=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: sa-p8
    type: kubernetes.io/dockerconfigjson
