---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgABThs/iohz7PuI0fTkFswjhrFpP8syXLc5lRgXNErZ1DsHC23VN7QTRwi2j82jUUXyjux1n9r+0NmGJj1LgDAMA1s7uWndcOcwhbsxh5VBoIQLP6i4Zum5xZv/QuBGsRFZW8VDspy+Vs7Moc1E3JESpowjv2LvPendrfbBoaM1g0A+oNfy0i087oLICXuWflZY8+5QlBidVsIzZVXx8NjI0KyEE7xdmZBMScfixI7Rf7DAt4FzFBqIHGzDrYIivdzkMFE7rcuowosTGTiN9HJiNMRfrRc8E6u1FBx9iLamY1cPy2IwifITiz9wpchIv7T40FHSyTXzxSGA4JqO5pb92Nmh1g6dhyP8FU6mNfnbQXUAL3nw5kIqfEbxAhHMsbAOUwLg5as+mng8Si9S7buwYMLSAQ7MaQYAaiF06fWD63hCkG+EOassJKkMQfXKrCj9bJtKc1bSlg3oWVzhfCcxJSVC2FhHBNrhcoP/shzwPJhClsdWq0BR8lPzrugUwJIYhC3p83nTxqQNOcymuPqgQiSvKPC9m0LwBJHqKsYU0bLQLj0VV7nO8s/VnAzvCxy1UJFOEBKxzwAmi0De+H3GIEm6PrSpRjt7RmECXnRcSAdNiN70lDF6ueqkcK+2SSkmADz+mOFN8RUNxfdlw87nGBN7+mJv8QQ6jAVW50A5JJNA9LwdX3BfPIXRimE98K71KDuZV4iFsA0eYZeWp/WoMQN5I93E5DwkDsuZRiRO5MiW7NV0IVVE95E74mOJzbKOBHBIW6ODKZzClXQ7qKLwRXE5KRk7GMfr5lepOHLg1lkT6WOiHvOQ4cYjJk1o20Gtbwq9sYs1DJODVMaNfQ+y7wQtNLWKifflN/qJm5LSe3aZkyOzV1UF4aiOKOEGc2KSJT5iV91ibbsXpTI1IvfIPYPt2cL3kEENuQNfEOrvYy9bxtbWNjC8vc9pxbnrPQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
