---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgA1CPPV9XEv6dmzhFlVNw71mM1bcmMQzgge+OKZxtDGN9yh8ZgI/SqP9r8X+RTerKpjYQtMevN7e5u9d045UsH6TlNozB16NJGc8DmH3hggmSxfpphOCJ5crhtmdOudUQj6RpaaIuBHkyafN+UPRQgct7L1q/dE7ygy0IKqiplgQwK+zc07JRsd0J9cO8O29qL/91EiippX+79/6lKooeEwAzQsoBvJZQDY2rHgKFWNahQcmMNTAz0r+6SZPKopEg+QlnMZ3M5knXL06A58hn5jJYvR4hDFfF32CZB0/LN6dU0ZJdBdq1uJ12nVbfim6SrIlyrj7kNfnytyTSZVuqLi7M36H/2aJi2iqbnSZAOrJlZ0IQNM5H8raYKd5MWI/16ucRfc/hZPVM+5MNyTVh9p5lFvt4oYfxghVyyEJ/oT9HPVJjdH3wSivuVxbMs1yadVoFPi7cFEDyA5vUGMbwxfvidpU8pYNDogBXxUE7dsoMJgXtd8/FTQYCAiC7tvig0B4ZFJyRQtXD/BvTPgfw32bIBZ7s7pcW0EhbQ7c7JpGU3INt8QURsODHizr0zfBQRzRbtTeVHp213vMdknlBrYbZMR2EshiEDDOS1qumwE3BLJBl1ISdtA4J9yuRoXYXIKMMOiyXWcJkthsUzzdV6+GnkEc2/lqPPiiKSdZJETI6A8FvWopih47i6yRwnijkz151Zk4Zomko0vD/Q=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
