---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: p8-revert-watcher-secret
  namespace: sa-p8
spec:
  encryptedData:
    github-token: AgABv78PGVTrEyhZPBdwGxCuVno2gJ/4h2MH8vAEV3S8Svi1C9DN2oMSxkhmibRQP75KE3e7iK5KQIoH07maqoiPP9K8faT+oJ4DhCSWxpJqN99FlUb54pmouEEtRdCLGPSLKH19anw/4swWtWNL881/SSHo0N0Pj8jA7Q4aCvw5lBb+jKY/eqYD/n1K9BRIm5RJ3YGxQhgQa97XmNCizl67Qz2cyvV2bRBUqEWWCMysghje6yvtoa7OhqTcIOEha9v16jfHr5WXSPBcKCt7h3zNEpEKciDWZ5SMtE+fckeaWH/9R3F/+liYZm78mAtPKsys5jfbO2TTnNnU4/HIddWQnIjQrxhBjE6knTy1P9XxprwaBnixV90NJNYscvJrKyYuThMHpCCeatZ2jJa+StpesVzIoimCya9hM1iI9GXshBJ5jszlOcJiG68fhF+lUs6IOQ5xAHtYnYKwVSvsSqHAyn/81FEcxTOnCCeivYuAKbXxn1jtTr2Xzi2DQ8RBTLbdYerCv8DBEctbyoI/WNQTtxsoMi+dVETyr77DUcnuHjDnCOM2HYxkR7AMhfpA6wkbPhyoeTcdFFyJREpktngrIX5Mt7lCKjoup2dABRo09ug6le4QnoD6jY1zvni7zPrQwyW/rYTi7NWQbI8pLhYb+FtnAknWlHzy5h04iBeE/vR+gZP3PF7w+n2aJu7TZQUBRuMJMvaG03hrjNNP6A+mQHVKzfAkKJzQXQ==
  template:
    metadata:
      name: p8-revert-watcher-secret
      namespace: sa-p8
