---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: p8-revert-watcher-secret
  namespace: sa-p8
spec:
  encryptedData:
    github-token: AgAGcjoOsf+8sajHdtKjsuzprsgDxgXCoWgeIBi8rHVXyhdl0PQzmv1hpPjfBPNXZEWWekBLzKbpQGFMiv8ymi9BJj42PdmtbWLnh/STM0VxhjhyaCJ7uhTa2g41gDt+OZdTqCKQkOBQ3FwzvqzpWJ8FLd5W6Sv9Q8wZgGpthj3t1kLeIPB52naGE/QTzwydA40LhHboAiXID0jT2nrtWV0bgN+XsGqCakg3HumES6JkhMCge8PCXZFB+XnN8a79JFiziW7xkBLot1LtS14B6ONQKsmtiDxKkiC5Ajf5+MSFqvtTO5EcuapvWeeue2GhQA5QU9cGFWyUbsiboDSEvtRUavu6b/PjUqS1rYU719y3W00XFkA9aeUUK9KCZGTKqDKfUlY3RUqMayN26qN7PEr+kafuDf94IaKV4iPLnobMZyJD1a1Eee2iuJ026xLRj0Am5q6HVV2COpeI7ydDUS05EnjXzItwSiboUE4Z0fedPNKSS2ZurmD1Ctz094g+oY+xsvBXyv1xx/5NBByBoB0TO6gYvgmYpyUXFTXUNN68E08FGFq6YBX6HDOfjVV0Gypp9vXOg4smvVuIxiHTt2lr9Y0t4Z6+/EowYqcF49w5foP9Tv6pDw1DggZVDyGjZj6vg3ufmOw75IXavb9OEYqAKIBRBWQjQsEu0h/PaSi3cwXBP20Ep8xYxDaiXmtGaGSrCsfEZXJN4jrk6kSebI4M9tpAsQLm8IV/gYpFW/GbvcpLKnBfthc+N9+I29mCPQw4Mk/aoiAfOt5+3j5a/iB6hgcVMkKQYKRN9HEWKHojjhIVVARsrQRtlihOuJA=
  template:
    metadata:
      name: p8-revert-watcher-secret
      namespace: sa-p8
    type: Opaque
